Assignment_2
azaat/python_basic_programming pull request #1
Opened 2020-03-15 18:26 UTC by azaat

2020-03-15 18:31 UTC, azaat commented
@SpirinEgor, можете посмотреть вторую домашку

2020-03-16 14:40 UTC, SpirinEgor requested changes
Прогони через pep8-linter, есть несколько предупреждений

2020-03-16 14:40 UTC, SpirinEgor commented on assignment_2/server/assignment_2.py
> +import json
Есть несколько импортов, которые не используются

2020-03-16 14:40 UTC, SpirinEgor commented on assignment_2/server/assignment_2.py
> +    return render_template('index.html', bikes = bikes)
Flask действительно можно использовать, как frontend фреймворк. Но в качестве учебного задания мы всё-таки используем его на backend-е, с минимальной логикой на js.
Пусть функция возвращает `json`, а клиентская часть его обрабатывает и отображает.

2020-03-30 09:32 UTC, SpirinEgor approved these changes

2020-04-02 07:10 UTC, merged